# cargo-deny configuration for VecLite
# Checks licenses, dependencies, and security advisories

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]

# List of explicitly disallowed licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

# Lint level for when multiple versions of the same license are detected
multiple-versions = "warn"
# Lint level for when a license exception is encountered
exceptions = "deny"

[licenses.private]
# If true, ignores workspace crates that aren't published, or are only
# published to private registries
ignore = false

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
highlight = "all"

# List of crates that are allowed multiple versions
allow = [
    # Common crates that often have multiple versions
    { name = "windows_x86_64_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_i686_msvc" },
]

# List of crates to deny
deny = [
    # Crates with known security issues or poor maintenance
    { name = "openssl-sys", version = "<0.9.87" },
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "warn"
# The lint level for crates that have been yanked from their source registry
yanked = "warn"
# The lint level for crates with security notices
notice = "warn"
# A list of advisory IDs to ignore
ignore = [
    # Add any specific advisories to ignore here
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"

[sources.allow-registry]
# List of allowed registries
# Default is crates.io
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[sources.allow-git]
# List of allowed git repositories
allow-git = [
    # Add any allowed git dependencies here
]